env_file: ".env.development"
app:
  name: shop
  port: 8082
  host: 127.0.0.1
  debug: true
  key: $2a$10$a2dUNHVqX2dTGgBH4O.gleTL6Yno858AvJGBdBFWScJQ0V9.6bM0O
  otp_expiration_time: 4 #4 minute

db:
  driver: mysql
  port: 3306
  name: shop_go
  host: 127.0.0.1
  username: root
  password: root

upload:
  categories: "uploads/media/categories/"
  products: "uploads/media/products/"
  brands: "uploads/media/brands/"

kavenegar:
  api_key: ""

redis:
  hostname: 127.0.0.1
  port: 6379
  password: "secret"
  dialTimeOut: 5
  readTimeOut: 5
  writeTimeOut: 5
  poolSize: 10
  poolTimeOut: 15
  idleTimeOut: 5
  idleCheckFrequency: 500

mongodb:
  name: shop_mongo